### ISSUE TITLE
How you get this

### ISSUE THREAD

**Issue by saper-2** [lzto/RaspberryPi_KeDei_35_lcd_v62#1]
Hello,

First, Great respect for finding out the init sequence :smile: for this display. 👍  👏 

Would you mind sharing how you get the init sequence working?
There is topic on official raspberry pi forum concerning those infamous kedei spi displays :) :
https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=124961

There would be more people interested in you work :smile:

**Comment by lzto** [comment]
Hi,

There are two ways to get the sequence, basically,

1. If you go for the easiest one(if you have some hand tools like another board which has SPI with decent high speed slave mode support) that is to hookup a SPI slave to the SPI bus to sniff the data. I used the slave mode in sunxi-A64's SPI to do verification... though it seems to be too easy. see https://github.com/lzto/sunxi-a64-spi-slave-monitor.

2. what I did first was to disassemble the kernel blob and load it into IDA Pro to find the function which is used to do the display init and then use kgdb attach to RPI and setup break points to poke around so that I can know the branch conditions in the init function. You have to know a little bit  asm language and know how to use these tools, and the datasheet[RPI's] is a must, plus a little bit guessing. Then you got this sequence.

- Tong
edited:typo
